apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-users-config
  namespace: default
data:
  jwt-issuer: "fcg-users"
  jwt-audience: "fcg-clients"
  swagger-enabled: "true"
  aspnetcore-environment: "Production"
